apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: multi-module-cxf
  
parameters:
- description: Git Source Repository
  name: SOURCE_REPOSITORY
  value: https://github.com/abhi050392/cxf/
  required: true
- description: Git Source reference
  name: SOURCE_REF
  value: master
  required: true
  
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: cxf-multi
      delete: blog
    name: cxf-multi
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cxf-multi:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${SOURCE_REF}
        uri: ${SOURCE_REPOSITORY}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_ARGS_APPEND
          value: -pl spring-boot-cxf-multi-module --also-make
        - name: ARTIFACT_DIR
          value: spring-boot-cxf-multi-module/target/
        - name: MODULE_DIR
          value: spring-boot-cxf-multi-module
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:2.0
          namespace: openshift1
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status: {}
  
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: cxf-multi
      delete: blog
    name: cxf-multi
  spec:
    replicas: 1
    selector:
      deploymentconfig: cxf-multi
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: cxf-multi
          delete: blog
          deploymentconfig: cxf-multi
      spec:
        containers:
          image: cxf-multi
          imagePullPolicy: Always
          name: cxf-multi
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 384Mi
            requests:
              cpu: 250m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - cxf-multi
        from:
          kind: ImageStreamTag
          name: cxf-multi:latest
      type: ImageChange
    - type: ConfigChange
  status: {}
  
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: cxf-multi
      delete: blog
    name: cxf-multi
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: cxf-multi:latest
      generation: null
      importPolicy: {}
      name: latest
  status: {}

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: cxf-multi
      delete: blog
    name: cxf-multi
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: cxf-multi
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
    
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: cxf-multi
      delete: blog
    name: cxf-multi
  spec:
    to:
      kind: Service
      name: cxf-multi
    port:
      targetPort: 8080-tcp
  status: {}
